version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017

  backend:
    build:
      context: ./Backend
    restart: always
    ports:
      - 5000:5000
    #volumes:
    #  - ./Backend:/app
    #  - /app/node_modules
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 80:80
    #volumes:
    #  - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
